version: "3.8"

services:
  mqtt-simulator:
    build: .
    environment:
      #### Use host's MQTT broker for local testing, with Mosquitto or similar
      # - MQTT_BROKER=host.docker.internal
      # - MQTT_TOPIC=sensors/telemetry

      #### AWS IoT Core 
      - MQTT_BROKER=asyxev3w22pu2-ats.iot.us-west-1.amazonaws.com
      - MQTT_TOPIC=sensors/telemetry
      # DEVICE_ID can be added or left out to let the script generate a random one (refer to publisher.py)
    volumes:
      - ./certs:/certs:ro
    # Ignore this if not using Docker Swarm
    deploy: 
      mode: replicated
      replicas: 10   # 🔁 bump to more depending on how much your machine can handle, or using Fargate